name: superalpaca-hello-world-2
base: core22
version: '2.10'
summary: GNU Hello, the "hello world" snap
description: |
  GNU hello prints a friendly greeting.
grade: devel
confinement: devmode

parts:
  gnu-hello:
    plugin: nil
