name: superalpaca-hello-world-2
base: core20
version: '2.10'
summary: GNU Hello, the "hello world" snap
description: |
  GNU hello prints a friendly greeting.
grade: devel
confinement: devmode

architectures: [amd64, arm64]

parts:
  gnu-hello:
    plugin: nil
